apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: my-ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
  params:
    - name: git-url
      value: https://github.com/guhhammer/ci-cd-final-project.git
    - name: image-name
      value: us.icr.io/sn-labsassets/ci-cd-final-project:latest
    - name: app-name
      value: my-app
